### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tkg0125** [tkg0125/furima_28771#11]
機能実装が完了しHerokuへのデプロイも完了いたしました。
本番環境下での挙動確認をお願いいたします。

#URL
https://furima-28771.herokuapp.com/

#Basic認証のIDとパスワード
ID: 28771
password: furima

#出品者用のメールアドレスとパスワード
mail: a@a
password: aaa111

#購入者用のメールアドレスとパスワード
mail: b@b
password: aaa111

#PAYJPテストカード
カード番号: 4242424242424242
期限: 12月 24年
CVC: 123

**Comment by mutorisa** [comment]
塚本さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
